name: Publish NuGet Package
on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x.x'

    - name: Restore dependencies
      run: dotnet restore ./Codecell.Component.Blazor/Codecell.Component.Blazor.csproj

    - name: Build main project
      run: dotnet build ./Codecell.Component.Blazor/Codecell.Component.Blazor.csproj --configuration Release --no-restore

    - name: Pack NuGet package
      run: dotnet pack ./Codecell.Component.Blazor/Codecell.Component.Blazor.csproj --configuration Release --no-build --output ./nupkg

    - name: Setup NuGet API key
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}

    - name: Publish to NuGet.org
      run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
